// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVbtLq-cEThGCDtIzOjEbg5OycR1CIYI',
    appId: '1:956481218713:web:551b26e5d5e2b428227008',
    messagingSenderId: '956481218713',
    projectId: 'firebase-test-20221107',
    authDomain: 'fir-test-20221107.firebaseapp.com',
    storageBucket: 'firebase-test-20221107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgmDIMcgrzk2E0VMMDzfYnZ8b1MdA6xvg',
    appId: '1:956481218713:android:49b20ef41e152a21227008',
    messagingSenderId: '956481218713',
    projectId: 'firebase-test-20221107',
    storageBucket: 'firebase-test-20221107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqiKkOzddwLP-gqXV6VvudZnWMJHNwv_E',
    appId: '1:956481218713:ios:c78793f0310e4376227008',
    messagingSenderId: '956481218713',
    projectId: 'firebase-test-20221107',
    storageBucket: 'firebase-test-20221107.appspot.com',
    iosClientId: '956481218713-ojrmiq7a7d4f080tc789pun1lp8fa5hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqiKkOzddwLP-gqXV6VvudZnWMJHNwv_E',
    appId: '1:956481218713:ios:c78793f0310e4376227008',
    messagingSenderId: '956481218713',
    projectId: 'firebase-test-20221107',
    storageBucket: 'firebase-test-20221107.appspot.com',
    iosClientId: '956481218713-ojrmiq7a7d4f080tc789pun1lp8fa5hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebase',
  );
}
